name: Build

on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  get-kernel:
    runs-on: image-builders
    outputs:
      kernel_version: ${{ steps.get-kernel.outputs.kernel_version }}
    steps:
    - id: get-kernel
      run: |
        echo "Kernel version $(uname -r)"
        echo "::set-output name=kernel_version::$(uname -r)"

  build-el8:
    runs-on: image-builders
    needs: get-kernel
    container:
      image: quay.io/ovirt/buildcontainer:el8stream
      options: --privileged --rm -v /lib/modules/${{ needs.get-kernel.outputs.kernel_version }}:/hostmodules

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      env:
        KERNEL_VERSION: ${{ needs.get-kernel.outputs.kernel_version }}
        EXTRACT_INSTALL_LOGS: yes
      run: |
        echo "k: ${KERNEL_VERSION} ${{ needs.get-kernel.outputs.kernel_version }}"
        ./build.sh

    - name: Upload rpm to resources.ovirt.org
      uses: ovirt/ovirt-resources-upload-action@main
      with:
        username: ${{ secrets.SSH_USERNAME_FOR_RESOURCES_OVIRT_ORG }}
        key: ${{ secrets.SSH_KEY_FOR_RESOURCES_OVIRT_ORG }}
        known_hosts: ${{ secrets.KNOWN_HOSTS_FOR_RESOURCES_OVIRT_ORG }}
        source: tmp.repos/RPMS/noarch/*.rpm
        target: github-ci/ovirt-node-ng-image/el8
        cleanup: yes
        createrepo: yes
        # keep 10 last builds + repodata
        keep_files_count: 11

    - name: Upload logs and manifests to github
      uses: actions/upload-artifact@v2
      with:
        name: logs-and-manifests
        path: |
          exported-artifacts

