name: Build

on:
  workflow_dispatch:
    inputs:
      keep_workdir:
        description: set to anything to keep around the work directory for inspection after the job finishes
        required: false
      extract_install_logs:
        description: set to anything to save anaconda logs and remove from rpm/iso
        required: false
      finalbuild:
        description: set to \"True\" for a final build
        required: true
        default: "False"
  push:
    branches: [master]

jobs:
  get-kernel:
    runs-on: image-builders
    outputs:
      kernel_version: ${{ steps.get-kernel.outputs.kernel_version }}
    steps:
    - id: get-kernel
      run: |
        echo "Kernel version $(uname -r)"
        echo "::set-output name=kernel_version::$(uname -r)"

  build-el8:
    runs-on: image-builders
    needs: get-kernel
    container:
      image: quay.io/ovirt/buildcontainer:el8stream
      options: --privileged --rm -v /lib/modules/${{ needs.get-kernel.outputs.kernel_version }}:/host/modules

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      env:
        EXTRACT_INSTALL_LOGS: ${{ github.event.inputs.extract_install_logs }}
        FINALBUILD: ${{ github.event.inputs.finalbuild }}
        SUPERMIN_MODULES: /host/modules
        SUPERMIN_KERNEL: /host/modules/vmlinuz
      run: ./build.sh

    - name: Upload rpm to resources.ovirt.org
      uses: ovirt/ovirt-resources-upload-action@main
      with:
        username: ${{ secrets.SSH_USERNAME_FOR_RESOURCES_OVIRT_ORG }}
        key: ${{ secrets.SSH_KEY_FOR_RESOURCES_OVIRT_ORG }}
        known_hosts: ${{ secrets.KNOWN_HOSTS_FOR_RESOURCES_OVIRT_ORG }}
        source: tmp.repos/RPMS/noarch/*.rpm
        target: github-ci/ovirt-node-ng-image/el8
        cleanup: yes
        createrepo: yes
        # keep 10 last builds + repodata
        keep_files_count: 11

    - name: Upload iso to resources.ovirt.org
      uses: ovirt/ovirt-resources-upload-action@main
      with:
        username: ${{ secrets.SSH_USERNAME_FOR_RESOURCES_OVIRT_ORG }}
        key: ${{ secrets.SSH_KEY_FOR_RESOURCES_OVIRT_ORG }}
        known_hosts: ${{ secrets.KNOWN_HOSTS_FOR_RESOURCES_OVIRT_ORG }}
        source: ovirt-node-ng-installer-*.iso
        target: github-ci/ovirt-node-ng-image
        cleanup: yes
        createrepo: no
        # keep 20 last builds
        keep_files_count: 20

    - name: Upload logs and manifests to github
      uses: actions/upload-artifact@v2
      with:
        name: logs-and-manifests
        path: |
          exported-artifacts

    - name: Clean up entire workdir
      if: always()
      run: |
        [[ -z "${{ github.event.inputs.keep_workdir }}" ]] && rm -rf $PWD/*
